### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by abitdodgy** [rung-tools/pagarme-elixir#1]
Do you plan on actively developing this lib? If not, please consider erasing it or making it private until you plan on working on it to avoid misleading fellow devs into thinking an integration exists. If you are interested in developing this further, let's talk.

**Comment by cuchi** [comment]
Hi!
We will eventually make progress in this project as long we have the time and it fits our need.

It will not be deleted, as it is open to **constructive** contribuitions. Feel free to open a pull request or an issue with some ideas, if it is good, we will gladly accept it!

We can make it private, but you will have to pay our subscription if you really want it.

**Comment by abitdodgy** [comment]
@cuchi first of all, thank you for taking the time to contribute to open source.

> We will eventually make progress in this project as long we have the time and it fits our need.

Allow me to ask you if you only intend to work on this if you have time and it fits your needs, why leave an empty lib with no code? Perhaps I fail to see it, and maybe you can help me understand, how is it useful to you or anyone? I'm only afraid that it might mislead other developers into thinking there's an integration (when there isn't), or worse, discourage others from developing their own integration.

For this reason, I think it's best to make it private until you make some progress on it. You can then open source it again and people will be more comfortable contributing to a project that already adds value to our community.

Cheers!

**Comment by cuchi** [comment]
@abitdodgy I totally understand your point of view, it is really frustrating when we search for something nice, but then we find something and it is barely or not implemented, sorry about that.

Since you've talked about it, we can look foward to start with some features ASAP.
Their public API is pretty big (https://docs.pagar.me/reference), if is there any feature you need the most at the moment, you can give some advice from where we should start. In this case you can refer either to me or to @haskellcamargo, which came up with the idea to create this repository.

And again, you are more than welcome and encouraged to contribute. 
Thanks!
